st102/2020-1st-St102-Algorithm-Sprint

week_00/dglee/test.c, week_00/dglee/test.md
0주차 test.md and test.c 완료했습니다.
=> add test.c and test.md

.idea/codestream.xml, week_01/backjoon/thkwon/200824_thkwon_fibonacci.md, week_01/backjoon/thkwon/200824_thkwon_fibonacci.py, week_01/backjoon/thkwon/200824_thkwon_fibonacci_with_dp.py
=> add fibonacci week01-backjoon-01

week_01/code_wars/cmSon/200824_vowel_count.md, week_01/code_wars/cmSon/Vowels.java
add 200824_vowel_count.md Vowel.java
테스트 코드를 작업 환경을 설정하는법을 아직 찾지 못해 따로 파일을 만들지 못했습니다ㅠㅠ
다음에는 더 공부하여 테스트 코드 파일도 같이 올리겠습니다.
=> cmSon 200824 codewars: Vowel Count

week_01/code_wars/dglee/200824_vowel_count.java, week_01/code_wars/dglee/200824_vowel_count.md
1주차 200824_vowel_count.java
200824_vowel_count.md 완료하였습니다.
=> add 200824_vowel_count.java 200824_vowel_count.md

week_01/code_wars/chSung/200824_vowel_count.java, week_01/code_wars/chSung/200824_vowel_count.md
01주차 Code wars Vowel Count 문제 풀었습니다 :)
=> add 200824_vowl_count files

week_00/jhkim/test.cpp, week_00/jhkim/test.md
0주차 test.md and test.cpp 완료하였습니다.
=> add test.md and test.cpp

week_01/code_wars/cmSon/200825_multiples_of_3_or_5.md, week_01/code_wars/cmSon/Mutiples.cpp
add Multiples.cpp 200825_multiples_of_3_or_5.md
자바로 하려했는데 자바에 대한 이해도가 많이 부족한거 같아서 c++로 하겠습니다 ㅠㅠ
=> Cm son week 01 02

week_01/code_wars/chSung/200825_multiples_of_3_or_5.java, week_01/code_wars/chSung/200825_multiples_of_3_or_5.md
01주차 Code wars multiples of 3 or 5 문제 풀었습니다 :)
=> add 200825_multiples_of_3_or_5 files

week_01/code_wars/jwlee/num_of_vowels.cpp, week_01/code_wars/jwlee/num_of_vowels.md
number of vowels 01주차 첫번째 과제 제출!!!
=> Add num_of_vowels.cpp and md

week_01/code_wars/jwlee/multiples_of_3or5.cpp, week_01/code_wars/jwlee/multiples_of_3or5.md
=> Add multiples_of_3or5

week_01/code_wars/sylee/Multiples_3_or_5.md, week_01/code_wars/sylee/Multiples_3_or_5.py
=> "Add Multiples of 3 or 5.py and Multiples of 3 or 5.md"

week_01/code_wars/myeong/200825_Multiples.cpp, week_01/code_wars/myeong/200825_Multiples.md
add 200825_Multiples.cpp and 200825_Multiples.md
=> add 200825_Multiples.cpp and 200825_Multiples.md

week_01/code_wars/thkwon/200826_even_or_odd.md, week_01/code_wars/thkwon/200826_even_or_odd.py
=> add codewars even_or_odd

week_01/code_wars/dglee/Multiples.java, week_01/code_wars/dglee/Multiples.md
=> add Multiples.java Multiples.md

week_01/code_wars/dglee/Even_or_Odd.java, week_01/code_wars/dglee/Even_or_Odd.md
=> add Even_or_Odd.java Even_or_Odd.md

week_01/code_wars/sylee/Even_or_Odd.md, week_01/code_wars/sylee/Even_or_Odd.py
=> Add Even_or_Odd.py and Even_or_Odd.md

week_01/code_wars/shhong/200826_Even_or_Odd.md, week_01/code_wars/shhong/200826_Even_or_Odd.py
=> Add 200826_Even_or_Odd.md and 200826_Even_or_Odd.py

week_01/code_wars/chSung/200826_even_or_odd.java, week_01/code_wars/chSung/200826_even_or_odd.md
01주차 Code wars even or odd 문제 풀었습니다 :)
=> add 200826_even_or_odd files

week_01/code_wars/thkwon/200827_find_the_odd_int.md, week_01/code_wars/thkwon/200827_find_the_odd_int.py
add code wars week01-04 find the odd int 완료
=> add code wars week01-04 find the odd int

.gitignore, .idea/2020-1st-St102-Algorithm-Sprint.iml, .idea/misc.xml, week_01/backjoon/thkwon/200827_thkwon_self_number.md, week_01/backjoon/thkwon/200827_thkwon_self_number.py
add thkwon week-01-backjoon-04 self_number 완료!
=> add thkwon week-01-backjoon-04 self_number

week_01/code_wars/sylee/200827_Find_the_odd_int.md, week_01/code_wars/sylee/200827_Find_the_odd_int.py
week-01-04 Find_the_odd_int 완료했습니다.
=> Add 200827_Find_the_odd_int.md and 200827_Find_the_odd_int.py

week_01/code_wars/cmSon/200826_Find_the_odd_int.md, week_01/code_wars/cmSon/200827_Find_the_odd_int.md, week_01/code_wars/cmSon/Find_the_odd_int.cpp
add 200827_Find_the_odd_int.md or Find_the_int_odd.md
=> Cm son week 01 04

week_01/backjoon/jhlee/week1_03.cpp, week_01/backjoon/jhlee/week1_03.md
=> add week1_03.cpp week1_03.md

week_01/backjoon/jihlee/DFSBFS.cpp, week_01/backjoon/jihlee/fibonacci5.cpp, week_01/backjoon/jihlee/fibonacci5.md, week_01/backjoon/jihlee/laboratory.cpp, week_01/backjoon/jihlee/laboratory.md, week_01/jihlee/laboratory.cpp, week_01/jihlee/laboratory.md
1주차 DFS와 BFS 완료했습니다. 
이번주 피보나치랑 연구실 이상한 폴더에 올려서 수정해서 지금 한번에 다시 올렸어요
merge는 이번꺼로만 할게요!
=> add dfsbfs.cpp and dfsbfs.md

week_01/code_wars/chSung/200827_find_the_odd_int.java, week_01/code_wars/chSung/200827_find_the_odd_int.md
01주차 Code wars fine the odd int 문제 풀었습니다 :)
=> add 200827_find_the_odd_int files

week_01/code_wars/myeong/200826_EvenorOdd.cpp, week_01/code_wars/myeong/200826_EvenorOdd.md
add 200826_EvenorOdd.md 200826_EverorOdd.cpp
=> add 200826_EvenorOdd.md 200826_EverorOdd.cpp

week_01/code_wars/mgSeong/200824_vowel_count.cpp, week_01/code_wars/mgSeong/200824_vowel_count.md
200824 Seong-Myeong week-01 solution by cpp
=> 200824 Seong-Myeong week-01 solution by cpp

week_01/code_wars/shhong/200827_Find _the _odd_int.md, week_01/code_wars/shhong/200827_Find _the _odd_int.py
=> Add 200827_Find the odd int

week_01/backjoon/jclim/fibonacci.cpp, week_01/backjoon/jclim/fibonacci.md
=> add fibonacci.cpp fibonacci.md

week_01/backjoon/jclim/dfs_bfs.cpp, week_01/backjoon/jclim/dfs_bfs.md, week_01/backjoon/jclim/self_number.cpp, week_01/backjoon/jclim/self_number.md
1주차 셀프 넘버 완료했습니다.
추가로 어제자 DFS와 BFS도 완료했습니다.
=> add self_number.cpp self_number.md

week_01/code_wars/thkwon/200828_get_the_middle_charater.md, week_01/code_wars/thkwon/200828_get_the_middle_charater.py
add thkwon week-01-codewars-05 get_the_middle_character 완료!
=> add thkwon week-01-codewars-05 get_the_middle_character

week_01/code_wars/shhong/200828_Get_the_middle_char.md, week_01/code_wars/shhong/200828_Get_the_middle_char.py
=> 200828 Get the middle character

week_01/code_wars/jwlee/find_the_odd_int.md
=> find_the_odd_int.java and md

week_01/code_wars/chSung/200828_Get_the_Middle_Character.java, week_01/code_wars/chSung/200828_Get_the_Middle_Character.md
01주차 Code wars Get the middle character 문제 풀었습니다 
형 코드워즈에 submit 할 때 양식? 같은게 있고 //여기서부터 코드쓰세요 이런 폼이 있는데 굳이 맞추지 않아도 되나요?
=> add 200828_Get_the_Middle_Character files

week_01/code_wars/thkwon/200829_disemvowel.md, week_01/code_wars/thkwon/200829_disemvowel_trolls.py
add thkwon week-01-codewars-06 disemvowel_trolls 완료~
=> add thkwon week-01-codewars-06 disemvowel_trolls

week_01/code_wars/sylee/200829_Disemvowel_Trolls.md, week_01/code_wars/sylee/200829_Disemvowel_Trolls.py
=> add week-01-06

week_01/code_wars/chSung/200829_Disemvowel_Trolls.java, week_01/code_wars/chSung/200829_Disemvowel_Trolls.md
01주차 Code Wars Disemvowel Trolls 문제 풀었습니다:)
휴일 잘 보내세요ㅎㅎ
=> add 200829_Disemvowel_Trolls files

week_01/code_wars/dglee/Disemvowel_Trolls.java, week_01/code_wars/dglee/Disemvowel_Trolls.md
=> Dglee week 01 06

week_01/code_wars/shhong/200829_Disemvowel_Trolls-Python.md, week_01/code_wars/shhong/200829_Disemvowel_Trolls-Python.py, week_01/code_wars/shhong/200829_Disemvowel_Trolls-Swift.md, week_01/code_wars/shhong/200829_Disemvowel_Trolls-Swift.swift
ios개발을 위해 swift와 python 두 방법으로 해보겠습니다!!!!!
=> Add Disemvowel_Trolls .py .md .swift

week_01/code_wars/cmSon/200828_Get_the_middle_character.md, week_01/code_wars/cmSon/Get_the_middle_character.cpp
add 200828_Get_the_middle_character.md and Get_the_middle_character.cpp
=> cmSon 200828 codewars:Get the middle character

.idea/2020-1st-St102-Algorithm-Sprint.iml, .idea/misc.xml, week_02/codewars/thkwon/200831_sum_of_digits_digital_root.md, week_02/codewars/thkwon/200831_sum_of_digits_digital_root.py
add digital_root codewars wekk_02_01완료~
=> add digital_root codewars wekk_02_01

week_01/code_wars/jwlee/disemvowel_trolls.java, week_01/code_wars/jwlee/disemvowel_trolls.md
=> Add disemvowel_trolls

week_01/code_wars/jwlee/get_the_middle_char.java, week_01/code_wars/jwlee/get_the_middle_char.md
=> Add get the middle character

week_01/code_wars/cmSon/200828_Get_the_middle_character.md, week_01/code_wars/cmSon/200831_Digital_Root.md, week_01/code_wars/cmSon/Digital_Root.cpp
add "Digitals_Root.cpp" and "200831_Digitals_Root.md"
=> cmSon 200831 codewars:Digitals Root

week_02/codewars/chSung/200831_sum_of_digits_digital_root.java, week_02/codewars/chSung/200831_sum_of_digits_digital_root.md
02주차 Code Wars sum of digits digital root 문제 풀었습니다!
=> add 200831_sum_of_digits_digital_root files

week_02/codewars/shHong/200831_Sum of Digits_Digital Root-Python.md, week_02/codewars/shHong/200831_Sum of Digits_Digital Root-Python.py, week_02/codewars/shHong/200831_Sum of Digits_Digital Root-Swift.md, week_02/codewars/shHong/200831_Sum of Digits_Digital Root-Swift.swift
=> Add 200831 Sum of Digits.py .swift. md

week_02/codewars/sylee/200831_Sum_of_Digits.md, week_02/codewars/sylee/200831_Sum_of_Digits.py
=> Add_week-02-01

week_02/myeong/200831_DigitalRoot.md
add 200831_DigitalRoot.cpp 200831_DigitalRoot.md
=> add 200831_DigitalRoot.cpp 200831_DigitalRoot.md

week_01/code_wars/myeong/200828_GetMiddle.cpp, week_01/code_wars/myeong/200828_GetMiddle.md, week_01/code_wars/myeong/200830_DisemvowelTrolls.cpp, week_01/code_wars/myeong/200830_DisemvowelTrolls.md
add 200830_DisemvowelTrolls.cpp 200830_DisemvowelTrolls.md
=> add 200830_DisemvowelTrolls.cpp 200830_DisemvowelTrolls.md

week_01/code_wars/myeong/200828_GetMiddle.cpp, week_01/code_wars/myeong/200828_GetMiddle.md
add 200828_GetMiddle.cpp 200828_GetMiddle.md 
저 성명근입니다.
엇 시험해보다가 브랜치를 제대로 못했네요.
죄송합니다. ㅠ
=> add 200828_GetMiddle.cpp 200828_GetMiddle.md

week_02/codewars/dglee/DRoot.java, week_02/codewars/dglee/DRoot.md
=> add DRoot.java DRoot.md

week_02/jwlee/Digital_root.java, week_02/jwlee/Digital_root.md
=> Add Digital_root

.idea/2020-1st-St102-Algorithm-Sprint.iml, .idea/misc.xml, week_02/backjoon/thkwon/line_up.py
add thkwon week-02-backjoon-01 line_up 완료!
=> add thkwon week-02-backjoon-01 line_up

week_02/codewars/thkwon/200901_who_likes.md, week_02/codewars/thkwon/200901_who_likes_it.py
Thkwon week 02 codewars 02 추가~
=> Thkwon week 02 codewars 02

week_02/codewars/chSung/200901_Who_likes_it.java, week_02/codewars/chSung/200901_Who_likes_it.md
02주차 code wars who likes it 문제 완료했습니다:)
=> add 200901_who_likes_it files

week_02/myeong/200901_WhoLikesIt.cpp, week_02/myeong/200901_WhoLikesIt.md
add 200901_WhoLikesIt.cpp 200901_WhoLikesIt.md
=> add 200901_WhoLikesIt.cpp 200901_WhoLikesIt.md

week_01/code_wars/cmSon/200901_Who_like_it.md, week_01/code_wars/cmSon/Who_likes_it.cpp
add "Who_like_it.cpp" and "200901_Who_like_it.md"
=> cmSon 200901 codewars:Who like it?

week_02/codewars/sylee/200901_who_likes_it.md, week_02/codewars/sylee/200901_who_likes_it.py
=> Add_week-02-02

week_02/codewars/shHong/200901_Who likes it-Python.md, week_02/codewars/shHong/200901_Who likes it-Python.py, week_02/codewars/shHong/200901_Who likes it-Swift.md, week_02/codewars/shHong/200901_Who likes it-Swift.swift
=> Add 200901 Who likes it.py .swift .md

week_02/codewars/jwlee/who_likes_it.java, week_02/codewars/jwlee/who_likes_it.md
=> Add who_likes_it

week_02/codewars/dglee/Solution.java, week_02/codewars/dglee/Solution.md
=> add Solution.java Solution.md

week_01/backjoon/jhkim/fibonacci5.cpp, week_01/backjoon/jhkim/fibonacci5.md
1주차 fibonacci5.cpp and fibonacci5.md 완료했습니다.
=> add fibonacci5.cpp and fibonacci5.md

week_02/codewars/chSung/200902_Create_phone_number.java, week_02/codewars/chSung/200902_Create_phone_number.md
02주차 code wars Creat phone number 완료했습니다!
형... 혹시 clever풀이가 이해가 안가는데 간단하게나마 알려주실수 있나요ㅠㅠ
=> add 200902_Creat_phone_number files

week_02/codewars/thkwon/200903_square_every_digit.py, week_02/codewars/thkwon/200903_square_every_digits.md
add code wars week02-04 square_every_digit 완료~
=> add code wars week02-04 square_every_digit

week_02/codewars/sylee/200902_Create_Phone_Number.md, week_02/codewars/sylee/200902_Create_Phone_Number.py
=> Add_week-02-03_agian

week_02/codewars/chSung/200903_Square_every_digit.java, week_02/codewars/chSung/200903_Square_every_digit.md
02주차 Code wars Square every digit 문제 완료했습니다~
=> add 200903_Square_every_digit files

week_02/backjoon/jclim/BOJ_1138.cpp, week_02/backjoon/jclim/BOJ_1138.md
=> add BOJ_1138.cpp BOJ_1138.md

week_02/backjoon/jclim/BOJ_10809.cpp, week_02/backjoon/jclim/BOJ_10809.md
=> add BOJ_10809.cpp BOJ_10809.md

week_02/codewars/shHong/200903_Square Every Digit-Python.md, week_02/codewars/shHong/200903_Square Every Digit-Python.py
=> Update 200903 Square Every digits

week_02/codewars/sylee/200903_Square_Every_Digit.md, week_02/codewars/sylee/200903_Square_Every_Digit.py
=> Add_week-02-04

week_02/codewars/cmSon/200903_Square_Every_Digits.md, week_02/codewars/cmSon/SquareDigit.java
add "Square_Every_Digits.md" and "SquareDigit.java"
=> cmSon 200903 codewars:Square Every Digits

week_02/codewars/dglee/SquareDigit.java, week_02/codewars/dglee/SquareDigit.md
=> add SquareDigit.java SquareDigit.md

week_02/codewars/chSung/200904_Highest_and_Lowest.java, week_02/codewars/chSung/200904_Highest_and_Lowest.md
02주차 Code wars Highest and Lowest 문제 완료했습니다:)
=> add 200904_Highest_and_Lowest files

week_02/backjoon/jclim/BOJ_1912.cpp, week_02/backjoon/jclim/BOJ_1912.md
=> add BOJ_1912.cpp BOJ_1912.md

week_02/backjoon/jclim/BOJ_1012.cpp, week_02/backjoon/jclim/BOJ_1012.md
=> add BOJ_1012.cpp BOJ_1012.md

week_02/backjoon/jclim/BOJ_11724.cpp, week_02/backjoon/jclim/BOJ_11724.md
=> add BOJ_11724.cpp BOJ_11724.md

week_02/codewars/cmSon/200904_Highest_adn_lowest.md, week_02/codewars/cmSon/higest_and_lowest.cpp
add "Highest_and_Loewst.cpp" and "200904_Highest_and_lowest.md"
=> cmSon 200904 codewars: Highest and lowest

week_02/codewars/sylee/200904_Highest_and_Lowest.md, week_02/codewars/sylee/200904_Highest_and_Lowest.py
=> Add week-02-05

week_02/codewars/myeong/200902_CreatPhoneNumber.cpp, week_02/codewars/myeong/200902_CreatPhoneNumber.md
add 200902_CreatPhoneNumber.cpp 200902_CreatPhoneNumber.md
=> add 200902_CreatPhoneNumber.cpp 200902_CreatPhoneNumber.md

week_02/codewars/myeong/200903_SquareEvery.md
add 200903_SquareEvery.py 200903_SquareEvery.md
이제 까지는 C++로 풀이하였으나 이번 문제에서 C++푸는게 없어 Python으로 풀었습니다.
=> add 200903_SquareEvery.py 200903_SquareEvery.md

week_02/codewars/myeong/200904_HighAndLow.cpp
add 200904_HighAndLow.cpp 200904_HighAndLow.md
=> add 200904_HighAndLow.cpp 200904_HighAndLow.md

week_02/codewars/sylee/200905_Mumbling.md, week_02/codewars/sylee/200905_Mumbling.py
=> Add week-02-06

week_02/codewars/jwlee/mumbling.java, week_02/codewars/jwlee/mumbling.md
=> Add mumbling

week_02/codewars/jwlee/Squaredigit.java, week_02/codewars/jwlee/Squaredigit.md
=> Jwlee week 02 04

week_02/codewars/shHong/200904_Highest and Lowest-Python.md, week_02/codewars/shHong/200904_Highest and Lowest-Python.py
=> Add 200903 Highest and Lowest.py .md

week_02/codewars/shHong/200904_Highest and Lowest-Python.md, week_02/codewars/shHong/200904_Highest and Lowest-Python.py, week_02/codewars/shHong/200905_Mumbling-Python.md, week_02/codewars/shHong/200905_Mumbling-Python.py
=> Shhong week 02 06

week_02/codewars/myeong/200905_Mumbling.md
add 200905_Mumbling.cpp 200905_Mumbling.md
=> add 200905_Mumbling.cpp 200905_Mumbling.md

week_02/codewars/dglee/High_Low.java, week_02/codewars/dglee/High_Low.md
=> add High_Low.java High_Low.md

week_02/backjoon/jclim/BOJ_7568.cpp, week_02/backjoon/jclim/BOJ_7568.md
=> add BOJ_7568.cpp BOJ_7568.md

week_02/codewars/shHong/200907_List Filtering-Python.md, week_02/codewars/shHong/200907_List Filtering-Python.py
=> Add 200907 List Filtering.py .md

week_03/codewars/myeong/200907_List_Filtering.md, week_03/codewars/myeong/200907_List_Filtering.py
add 200907_List_Filtering.md 200907_List_Filtering.py
=> add 200907_List_Filtering.md 200907_List_Filtering.py

week_03/codewars/chSung/200907_List_Filtering.cs, week_03/codewars/chSung/200907_List_Filtering.md
03주차 code wars List Filtering 문제 완료했습니다:)
요번꺼는 자바도 없는 것 같아요!
=> add 200907_List_Filtering files

week_03/codewars/sylee/200907_List_Filtering.md, week_03/codewars/sylee/200907_List_Filtering.py
=> Add week-03-01

week_03/backjoon/jclim/BOJ_11047.cpp, week_03/backjoon/jclim/BOJ_11047.md
=> add BOJ_11047.cpp BOJ_11047.md

week_03/codewars/thkwon/shortest_word.md, week_03/codewars/thkwon/shortest_word.py
add shortest word week_03 02 완료~
=> add shortest word week_03 02

week_03/codewars/sylee/200908_Shortest_Word.md, week_03/codewars/sylee/200908_Shortest_Word.py
=> Add week-03-02

week_03/codewars/myeong/200908_Shortest.cpp, week_03/codewars/myeong/200908_Shortest.md
add 200908_Shortest.cpp 200908_Shortest.md and remind
=> add 200908_Shortest.cpp 200908_Shortest.md and remind

week_03/codewars/jwlee/findshort.java, week_03/codewars/jwlee/findshort.md
=> Add findshort

week_02/codewars/cmSon/200904_Highest_adn_lowest.md, week_02/codewars/cmSon/200905_Mumbling.md, week_02/codewars/cmSon/Mumbling.cpp
add "200905_Mubling.md" and "Mubling.cpp"
eidt "Highest_and_lowest.cpp" - add Test code
=> cmSon 200905: Mumbling

week_03/backjoon/jclim/BOJ_2563.cpp, week_03/backjoon/jclim/BOJ_2563.md
=> add BOJ_2563.cpp BOJ_2563.md

week_03/codewars/thkwon/stop_gninnips.md, week_03/codewars/thkwon/stop_gninnips.py
add shortest word week_03 03 완료
=> add shortest word week_03 03

week_03/codewars/shHong/200909_Spin Words-Python.md, week_03/codewars/shHong/200909_Spoin words-Python.py
=> Add 200909 Spin Words.py .md

week_03/codewars/sylee/200909_Stop_gninnipS_My_sdroW.md, week_03/codewars/sylee/200909_Stop_gninnipS_My_sdroW.py
=> Add week-03-03

week_03/codewars/myeong/200909_Stop_spinning.md
add 200909_Stop_spinning.cpp 200909_Stop_spinning.md
=> add 200909_Stop_spinning.cpp 200909_Stop_spinning.md

week_03/codewars/thkwon/bit_counting.md, week_03/codewars/thkwon/bit_counting.py
add week-03 codewars bit_counting 완료
=> add week-03 codewars bit_counting

week_03/backjoon/jclim/BOJ_2667.cpp, week_03/backjoon/jclim/BOJ_2667.md
=> add BOJ_2667.cpp BOJ_2667.md

week_02/codewars/jwlee/phone_number.java, week_02/codewars/jwlee/phone_number.md
=> Add phone number

week_03/codewars/jwlee/spinwords.java, week_03/codewars/jwlee/spinwords.md
=> Add spinwords

week_04/codewars/shHong/200915_take ten minute walk.md, week_04/codewars/shHong/200915_take ten minute walk.py
=> Add 200915 take ten minute walk.py .md

week_04/codewars/shHong/200914_duplicate_encoder.md, week_04/codewars/shHong/200914_duplicate_encoder.py
=> Add 200914 duplicate encoder.py .md

week_04/codewars/sylee/200915_Take_a_Ten_Minute_Walk.md, week_04/codewars/sylee/200915_Take_a_Ten_Minute_Walk.py
=> Add week-04-02

week_03/codewars/myeong/200910_Bit_Counting.cpp, week_03/codewars/myeong/200910_Bit_Counting.md
add 200910_Bit_Counting.cpp 200910_Bit_Counting.md
=> add 200910_Bit_Counting.cpp 200910_Bit_Counting.md

week_03/codewars/myeong/200911_Find_The_Parity_Outlier.cpp, week_03/codewars/myeong/200911_Find_The_Parity_Outlier.md
add 200911_Find_The_Parity_Outlier.cpp 200911_Find_The_Parity_Outlier.md
=> add 200911_Find_The_Parity_Outlier.cpp 200911_Find_The_Parity_Outlier.md

week_04/codewars/shHong/200916_Tribonacci Sequence-python.md, week_04/codewars/shHong/200916_Tribonacci Sequence-python.py, week_04/codewars/shHong/200916_Tribonacci Sequence-swift.md, week_04/codewars/shHong/200916_Tribonacci Sequence-swift.swift
=> Add 200916_Tribonacci Sequence.py .swift .md

week_04/codewars/sylee/200916_Tribonacci_Sequence.md, week_04/codewars/sylee/200916_Tribonacci_Sequence.py
=> Add week-04-03

week_04/codewars/sylee/200917_Perfect_Square.md, week_04/codewars/sylee/200917_Perfect_Square.py
=> Add week-04-04

week_04/backjoon/jclim/BOJ_10026.cpp, week_04/backjoon/jclim/BOJ_10026.md
=> add BOJ_10026.cpp BOJ_10026.md

week_04/codewars/jwlee/perfect_square.java, week_04/codewars/jwlee/perfect_square.md
=> Add perfect square

week_03/codewars/dglee/Bit_Count.java, week_03/codewars/dglee/Bit_Count.md, week_03/codewars/dglee/Reverse_Word.java, week_03/codewars/dglee/Reverse_Word.md
3주차 수요일, 목요일 코드워즈 완료했습니다.
늦어서 죄송합니다 ㅜㅜ
=> add Bit_Count.java Bit_Count.md Reverse_Word.java Reverse_Word.md

week_03/codewars/dglee/Bit_Count.java, week_03/codewars/dglee/Bit_Count.md, week_03/codewars/dglee/FindOutlier.java, week_03/codewars/dglee/FindOutlier.md, week_03/codewars/dglee/Reverse_Word.java, week_03/codewars/dglee/Reverse_Word.md
=> Dglee week 03 05

week_05/codewars/shHong/200921_Equal side of an array.md, week_05/codewars/shHong/200921_Equal side of an array.py
=> Add 200921 Equal side of an array.py .md

week_04/backjoon/jclim/BOJ_4796.cpp, week_04/backjoon/jclim/BOJ_4796.md
=> add BOJ_4796.cpp BOJ_4796.md

week_05/backjoon/jclim/BOJ_1152.cpp, week_05/backjoon/jclim/BOJ_1152.md
=> add BOJ_1152.cpp BOJ_1152.md

week_03/codewars/cmSon/200910_bit_counting.md, week_03/codewars/cmSon/bit_counting.cpp
add "bit_counting.cpp" and "200910_bit_counting.md"
=> cmSon 200910 codewars : Bits Counting

week_03/codewars/cmSon/2009011_Find_The_Parity_Outlier.md, week_03/codewars/cmSon/find_outlier.cpp
add "200911_Find_the_Parity_Outlier.md" and "find_outlier.cpp"
=> cmSon 200911 codewars : Find the Parity Outlier
